'''
Created on September 3rd, 2015

@author: Aparna
'''
'''
This program is to read the text file containing closed frequent item sets generated by 
Christian Borgelt's Apriori implementation and to remove the item sets that does not 
contain the class label. 

The input to this program is a text file with each row containing a closed item set.
The output file is also a text file with only closed item sets that has the class label.
'''
from pandas import read_csv
import pandas as pd
import numpy as np
import os
import re
from collections import defaultdict
import csv
import math
import chi2Calculation
import ClosedItemSetProcessing
import ContrastRuleAnalysis
import InverseLabelRules

print "\nPlease enter a number corresponding to the dataset for which the rules are to be generated\n";
print "1 - Graduated dataset"
print "2 - Third term persistence dataset"
print "3 - Fifth term persistence dataset"
print "4 - Seventh term persistence dataset"
inputChoice = raw_input("\n\nEnter the choice")
inputdir = raw_input("Please enter the location of the input file(C:\Users\Aparna\Anaconda\AprioriResults)")
#outputdir = raw_input("Please enter the location where output needs to be saved(C:\Users\Aparna\Anaconda\AprioriResults)")
if (inputChoice=='1'):
	ClosedItemSetProcessing.callClosedItemSetProcessing(inputdir,"Graduated","Not-Graduated",0)
	ContrastRuleAnalysis.callContrastAnalysis(inputdir,"Graduated","Not-Graduated",0)
	InverseLabelRules.callInverseLabelRules(inputdir,"Graduated","Not-Graduated",0)
elif (inputChoice=='2'):
	ClosedItemSetProcessing.callClosedItemSetProcessing(inputdir,"Third-term-Persisted","Third-term-Not-Persisted",0.8)
	ContrastRuleAnalysis.callContrastAnalysis(inputdir,"Third-term-Persisted","Third-term-Not-Persisted",0.8)
	InverseLabelRules.callInverseLabelRules(inputdir,"Third-term-Persisted","Third-term-Not-Persisted",0.8)
		
elif (inputChoice=='3'):
	ClosedItemSetProcessing.callClosedItemSetProcessing(inputdir,"Fifth-term-Persisted","Fifth-term-Not-Persisted",0.8)
	ContrastRuleAnalysis.callContrastAnalysis(inputdir,"Fifth-term-Persisted","Fifth-term-Not-Persisted",0.8)
	InverseLabelRules.callInverseLabelRules(inputdir,"Fifth-term-Persisted","Fifth-term-Not-Persisted",0.8)
	
elif (inputChoice=='4'):
	ClosedItemSetProcessing.callClosedItemSetProcessing(inputdir,"Seventh-term-Persisted","Seventh-term-Not-Persisted",0.8)
	ContrastRuleAnalysis.callContrastAnalysis(inputdir,"Seventh-term-Persisted","Seventh-term-Not-Persisted",0.8)
	InverseLabelRules.callInverseLabelRules(inputdir,"Seventh-term-Persisted","Seventh-term-Not-Persisted",0.8)
	
else:
	print "Wrong Choice !!!! Try again !!!!"
